spring:
  application:
    name: ebi-masterdata-person-api
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
      driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
      
server:
  port: 8080
  servlet:
    context-path: /person