INSERT INTO PERSON (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, FAVOURITE_COLOR) VALUES (1, 'John', 'Wick', '29', 'red');
INSERT INTO PERSON (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, FAVOURITE_COLOR) VALUES (2, 'Sarah', 'Raven', '54', 'blue');

INSERT INTO PERSON_HOBBY (PERSON_PERSON_ID, HOBBY) VALUES (1, 'shopping');
INSERT INTO PERSON_HOBBY (PERSON_PERSON_ID, HOBBY) VALUES (1, 'football');
INSERT INTO PERSON_HOBBY (PERSON_PERSON_ID, HOBBY) VALUES (2, 'chess');